FROM node:16-alpine

WORKDIR /usr/src

EXPOSE 5000

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080
RUN node -v && npm -v && npm install && npm run build && npm install -g serve 

CMD ["serve","-s","-l","5000","build"]
